### ISSUE TITLE
Web interface for NS3

### ISSUE THREAD

**Issue by sr77in** [nsnam/ns-3-dev-git#10]
Wondering why no one seriously consider to have a web interface for NS3?  (I noticed one attempt for NS2 in  http://vlssit.iitkgp.ernet.in/ns2web/ns2web/# ).  Thinking of working on it using NodeJS and it's plugins for binding C++ libraries for NS3.  Any comments? If I'm developing as API modules, what will be best approach to proceed with? Thanks.

**Comment by tomhenderson** [comment]
Hi, the github issue discussion is not widely read, since this is not our main code repository.  I recommend that you subscribe to this developers list and then post your question there:
http://mailman.isi.edu/mailman/listinfo/ns-developers

There have been some attempts at web interface in the past.  I do not know the current status of them.  If you ask on that list you will get more feedback than here.
